name: Build and Release WindowsCleaner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild (Visual Studio 2022)
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '2022'

    - name: Restore NuGet packages (if any)
      run: nuget restore WindowsCleaner.sln

    - name: Build WindowsCleaner with MSBuild
      run: msbuild WindowsCleaner.sln /p:Configuration=Release /p:Platform=x64

    - name: Publish Build Artifacts
      run: |
        mkdir publish
        msbuild WindowsCleaner.sln /p:Configuration=Release /p:Platform=x64 /p:OutputPath=./publish

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WindowsCleaner-artifact
        path: ./publish/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: WindowsCleaner-artifact

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/**

    - name: Clean up
      run: rm -rf ./publish
